### ISSUE TITLE
HTTP status code checking

### ISSUE THREAD

**Issue by objectiveSee** [shernshiou/node-uber#12]
Currently the library does not check the HTTP status code returned from Uber API requests. The data.statusCode property would tell you whether there was a non 200 response. Uber will, for example, return a 409 when there is surge pricing in response to `POST /requests`. The response body contains enough info to determine that there is a surge w/o using the status code, but the status code may be nice to have as well. 

The smallest change would be to pass `data` into the callback in `Uber.js`. Another option is to check the statusCode in the response handler and create an error if the code is non-200. 

```js
  request.get({
    url: url,
    //auth: accessToken,
    json: true
  }, function (err, data, res) {

  // TODO: non-200 data.statusCode handling here!

    if (err) {
      callback(err);
    } else {
      callback(null, res, data);       // include `data` in callback
    }
  });
```

**Comment by agraebe** [comment]
@objectiveSee I identified that as an issue as well and proceeded with your second suggestion:

``javascript
  var localCallback = function localCallback(err, data, res) {

    // shared callback between put, post, patch, and delete requests

    if (err || data.statusCode >= 400) {

      callback(err, data);

    } else {

      callback(null, res);

    }

  };
``

It was pulled with the last PR and you will receive an error in case the HTTP status it is over 400. I chose 400 because 2xxand 3xx could be still considered as success. What's your perspective on that?

However, if the callback returns with an error, you can use the second parameters value to identify the exact HTTP status.

**Comment by agraebe** [comment]
@objectiveSee @shernshiou Just realized I missed the GET method. Bugfix is coming with [PR #19](https://github.com/shernshiou/node-uber/pull/19).
