### ISSUE TITLE
Functionality for Surge Pricing

### ISSUE THREAD

**Issue by ccbeyer** [shernshiou/node-uber#35]
Would love to have the functionality for surge pricing, which would include:
-Getting surge pricing confirmation id from HTTP 409 error
-Ability to pass back surge confirmation id in request 

Thanks!

**Comment by agraebe** [comment]
Will surely looks into it! Did you implement it yourself already? Would love to see your approach to this. Might be helpful for the draft of a user-friendly / native solution.

**Comment by agraebe** [comment]
@kp96 mind taking a look at this? :)

**Comment by kp96** [comment]
Will get started on it asap :+1:

**Comment by kp96** [comment]
I have modified to the `Requests.js` `create` method to include support for this feature. Here's a gist of what I did.

1.  Added response handling from the `Uber.post` method by moving the code to `localCallback` inside `create` method.
2. The `create` method first checks if the parameter supplied is `surge_confirmation_id`. If it is so, then the request is directly made and the response is handled in the `localCallback`. If not, it proceeds to normal `geocoded` request.
3.  The `localCallback` method checks if the `response.statusCode` is `409` and also verifies that the error is due to the `surge_confirmation`. Then `surge` data is sent via `callback`.

This is  pretty much about the feature. I also had to change the testing part to accommodate this feature. Here's the gist

1. Added `product_id` based `nocks` to differentiate various `requests`
2. Added `tests` for both `callback based` and `async based`. 

I have made the assumption that  `surge_confirmation_id` alone is sufficient for requesting a ride. I have read about it [here](https://developer.uber.com/docs/rides/api/v1-requests). The modified `create` can be accessed like this.

````
uber.requests.create(params, function (err, res, surge) {
    if (surge) {
        console.log(surge.surge_confirmation_id);
        //getApproval is a dummy method
        getApproval (surge.href, function(accept) {
              if (accept) {
                  uber.requests.create({
                         'surge_confirmation_id' : surge.surge_confirmation_id'
                          }, callback);
        }
     }
}
````
Kindly intimate if there is any problem with this approach. If all is well, I can raise a PR.

**Comment by agraebe** [comment]
Hey @kp96, thanks for working this out! I really like to have surge integrated as seamless as possible - do you think we need to add a surge parameter to the response? Could we get to something like this (example):

```
uber.requests.create(params, function (err, res) {
    if(err) {
       // getApproval is a dummy method
        uber.isSurge(err) ? getApproval(err.surge_confirmation.href) : console.rr(err);
    } 
...
}
```

And a new method just to handle surge - maybe even without any required parameter, like so:
```
uber.requests.acceptSurge(callback)
```

The uber object could store the most recent surge_confirmation_id (along with all other parameters) in the background, so there is no need to explicitly communicate the same data. What do you thinnk?

**Comment by kp96** [comment]
@agraebe 
Your solution looks more elegant. I will make the changes accordingly. :)

**Comment by kp96** [comment]
@agraebe 
I've made the changes. The latest commit to my fork is [here](https://github.com/kp96/node-uber/commit/1ae04ab4bddfa7fb0d159279817637564ee9fe68). Let me know if any changes are needed. Thanks

**Comment by agraebe** [comment]
@kp96 sorry for the super late response! Would you mind creating a PR in this project? Thanks!

**Comment by kp96** [comment]
Done :+1:
