### ISSUE TITLE
Add mechanism for token renewal

### ISSUE THREAD

**Issue by agraebe** [shernshiou/node-uber#44]
Uber object should store the token expiration date and renew the OAuth 2.0 access_token if date is reached

**Comment by kp96** [comment]
Hi, I would like to work on this. Kindly give me some suggestions to proceed.

**Comment by agraebe** [comment]
@kp96 Love it! I would recommend the following:

- check out [branch v1.0.0](https://github.com/shernshiou/node-uber/tree/v1.0.0). That way, we don't need to change your submission for the v1. There's quite some difference in terms of source code. You should get familiar with it
- try to understand what [Uber.js](https://github.com/shernshiou/node-uber/blob/v1.0.0/lib/Uber.js) does. Most important, it uses the OAuth library to get the token
- for the token renewal, you need to check for each HTTP call, if the existing token is still valid. You could integrate that check within the ``modifierMethodHelper`` method. The property ``tokenExpiration`` should be used for that
- if renewal is required, use the method ``authorization`` with the property ``refresh_token``. After that, execute the HTTP call as usual

As soon as you have the feature implemented, I'd ask you to add some tests. One test for the old-fashioned (node-back style) calls in this file: [``oauth.js``](https://github.com/shernshiou/node-uber/blob/v1.0.0/test/oauth.js) and one test for the new async (promise-based) calls in this file: [``oauthAsync.js``](https://github.com/shernshiou/node-uber/blob/v1.0.0/test/oauthAsync.js).

Let me know if you have any further questions. Super excited to get on board as a contributor :)

**Comment by kp96** [comment]
Thanks, That is all I needed as of now. Will start working on it asap.

**Comment by agraebe** [comment]
👍

**Comment by kp96** [comment]
Hi, 
As per your suggestions. I made the following changes.

1. Added a method `isTokenStale()` that checks if token is expired. Followed the `500` sec threshold as in the `uber python sdk`
2. Inside the `modifierMethodHelper`, I checked if the token is stale and if it is, I called the `authorization` method with `refresh_token` property.
3. Due to rest of the code being synchronous and only the refresh part is asynchronous I have moved the code into a function `refreshCallback` and called it after execution completes. I took this idea from [here](http://stackoverflow.com/questions/13096856/conditionally-call-async-function-in-node)

However, I faced some issues regarding the `tests` part. The problem is I am very new to `tdd` and writing tests. I tried to manually check if the token refresh is happening by explicitly returning `true` from `isTokenStale()` method. I got this error from `nock`.

`AssertionError: expected [Error: Nock: No match for request` for every request method like `PUT`, `POST` and so on.. I tried to understand `Nock` library but not able to figure out the exact error. I have pushed the commit [here](https://github.com/kp96/node-uber/commit/4d55a90be1ff8dd7ebca31e87cfed0ea7f090fd6). Kindly help me out with it and pardon me  if it sounds too silly.

**Comment by agraebe** [comment]
@kp96 sounds great. Let's push through and get the testing issue out of the way! I quickly checked out your commit and ran the tests with this result:
```
  264 passing (1s)

----------------|----------|----------|----------|----------|----------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------|----------|----------|----------|----------|----------------|
 lib/           |    97.83 |    92.31 |    96.88 |    97.83 |                |
  Uber.js       |    97.83 |    92.31 |    96.88 |    97.83 | 199,200,203,204 |
 lib/resources/ |      100 |      100 |      100 |      100 |                |
  Estimates.js  |      100 |      100 |      100 |      100 |                |
  Payment.js    |      100 |      100 |      100 |      100 |                |
  Places.js     |      100 |      100 |      100 |      100 |                |
  Products.js   |      100 |      100 |      100 |      100 |                |
  Reminders.js  |      100 |      100 |      100 |      100 |                |
  Requests.js   |      100 |      100 |      100 |      100 |                |
  User.js       |      100 |      100 |      100 |      100 |                |
----------------|----------|----------|----------|----------|----------------|
All files       |    99.01 |    96.61 |    98.84 |    99.01 |                |
----------------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 99.01% ( 400/404 )
Branches     : 96.61% ( 228/236 )
Functions    : 98.84% ( 85/86 )
Lines        : 99.01% ( 400/404 )
================================================================================
```

As you can see, your additions show up as untested code lines (199,200,203,204). We'd need to test these to maintain a great coverage.

I didn't come across any errors with running the tests. However, this error you describe usually indicates that the mock server ("nock") we use for testing can't find the route you try to address. 

- did you run ``npm install``?
- did you update to the latest revision of the code?
- do you run test with ``npm test``?


I see that your test is quite complicated. In general, in order to test your more or less edge case, you'd need to:
- add a new sample response file containing a token that has an ``expires_in`` value in the past. The file should be very similar to ``test/replies/token.json``.

- update the ``test/allTests.js`` and add a new nock, for instance:
```
.post('/oauth/token', {
            code: <your_new_code>
        })
        .replyWithFile(200, jp('<your_new_token_filename_without_extension>'))
```
> It's important to understand that we use nock to check for the route ('/oauth/token') and for the submitted headers ('code') in order to match a route.

You have to replace ``<your_new_code>`` with some code that you'd use to target nock to a new route with the expired token response file you saved as ``<your_new_token_filename_without_extension>``. We store all tokens in the ``test/common.js`` file. Add your new token and update the top require command in ``test/allTests.js`` to import your token. With that, you added a new route for a specific oauth token. Nock will respond with the expired token file. Great! Now, you should strat writing the unit tests.

- update the file ``test/oauth.js`` and add a new ``describe`` part containing at leats one ``it`` unit test. Essentially, you'd describe a new authorization process. Within this test, you'd need to use your new code you added to ``test/common.js``. Therefore, update the require command on top to add your new code. Then, in the ``it`` test, you essentially run an authorization command with that new token:
```
uber.authorization({
                authorization_code: <your_new_code>
            },
            function(err, res) {
```
In the callback, you'd have received the expired token. Now comes the interesting part. You have to make some call (any, let's call that call2). Your new feature should realize that the token is outdated and make a new call with a refresh_token to the login page of Uber. You might need to add another route to nock with your new refresh_token. As soon as your request is finished, in the callback of call2 you should check if the Uber object has a new, valid acess_token and an expiration date in the future.

- similarly to what you did in the ``test/oauth.js`` file, you'd need to update the ``test/oauthAsync.js`` file. This file tests the async variants of the methods you updated. There should be no surprises here. The methods just don't have callbacks but promises you need to use. Keep in mind, every async method name appends with "Async".

That's quite an advanced test case you chose there buddy :) Let me know if you can get it done. Otherwise, I'll PR the tests to your fork and you can take these for your final PR :)

**Comment by kp96** [comment]
@agraebe Thanks for taking your time in giving me precise instructions. I will try to write tests on my own and if I face any issue, I will let you know. :+1:

**Comment by kp96** [comment]
@agraebe I have implemented all the tests as you described and completed the code coverage. Below is a gist of what I did.

1. Added required files in the `test/replies` folder.
2. Added required codes for various `nocks` in the `common.js` file and used them wherever required.
3. After getting an `expired_token` response from `nock`,  I called the `uber.request` method that  requires the `access_token`, and after the `callback` is called I have checked whether `token_refresh` happened or not.
4. Added an additional case where `uber server` may not be available during `token_refresh`, so that complete code is covered.
5. Added the above tests in both `test/oauth.js` and `test/oauthAsync.js` with their respective variants.

The latest updated commit in my fork is [here](https://github.com/kp96/node-uber/commit/982999ebb5789128d8c212670e86b7c14dcea14d). Let me know if anything else needs to be done. If that is all is needed, I will raise a PR. Thanks for your suggestions.

**Comment by kp96** [comment]
Should I raise a Pull Request?  A gentle reminder. Thanks

**Comment by agraebe** [comment]
@kp96 Sorry for the late response! Your contribution looks great! Just create a PR and we can merge it after passing the tests... Are you interested in further tasks? We have some more in the backlog and are looking for passionate devs like you :)

**Comment by kp96** [comment]
Thanks! Yes, I am excited to take more tasks. :)
