### ISSUE TITLE
how to set access_token

### ISSUE THREAD

**Issue by Jan-Jan** [shernshiou/node-uber#46]
First off, thank you very much for node-uber!!

I was wondering how do I set an `access_token` on requests that require OAuth?

**Comment by agraebe** [comment]
@Jan-Jan you're very welcome! By saying "set an access_token", do you mean without actually going through the process of obtaining one? If you want to get an access_token first, the steps in the README guide you exactly through that process. Otherwise, you can manually override the access_token in the Uber object: ``uber.access_token``.

**Comment by tjhorner** [comment]
Does setting `uber.access_token` still work in the current version? It doesn't for me. Any requests that require OAuth give an `invalid_grant` error.
